import express from 'express';
import { createClient } from '@supabase/supabase-js';
const app=express();
app.disable('x-powered-by');
app.use((req,res,next)=>{const origin=process.env.CLIENT_URL||'http://localhost:5173'; res.setHeader('Access-Control-Allow-Origin',origin); res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization'); res.setHeader('Access-Control-Allow-Methods','GET, POST, PATCH, OPTIONS'); if(req.method==='OPTIONS') return res.sendStatus(204); next();});
app.use(express.json({ limit: '100kb' }));
const admin=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
async function requireAdmin(req,res,next){const token=req.headers.authorization?.replace('Bearer ',''); if(!token)return res.status(401).json({error:'Authentication required'}); const {data:{user},error}=await admin.auth.getUser(token); if(error||!user)return res.status(401).json({error:'Invalid session'}); const {data:profile}=await admin.from('profiles').select('role').eq('id',user.id).single(); if(profile?.role!=='admin')return res.status(403).json({error:'Admin access required'}); req.user=user; next();}
app.post('/api/users',requireAdmin,async(req,res)=>{const {email,password,fullName,role='teacher'}=req.body; if(!email||!password||!fullName||!['admin','teacher'].includes(role))return res.status(400).json({error:'Valid email, password, fullName and role are required'}); const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName,role}}); if(error)return res.status(400).json({error:error.message}); const {error:profileError}=await admin.from('profiles').insert({id:data.user.id,full_name:fullName,role}); if(profileError)return res.status(400).json({error:profileError.message}); res.status(201).json({user:data.user});});
app.get('/api/classes',async(_req,res)=>{const {data,error}=await admin.from('classes').select('*').order('name'); res.status(error?400:200).json(error?{error:error.message}:data);});
app.get('/api/classes/:id/students',async(req,res)=>{const {data,error}=await admin.from('enrollments').select('student:students(*), grades(*)').eq('class_id',req.params.id); res.status(error?400:200).json(error?{error:error.message}:data);});
app.patch('/api/grades/:id',async(req,res)=>{const {grade,feedback}=req.body; const {data,error}=await admin.from('grades').update({grade,feedback,updated_at:new Date().toISOString()}).eq('id',req.params.id).select().single(); res.status(error?400:200).json(error?{error:error.message}:data);});
app.listen(process.env.PORT||5000,()=>console.log(`API running on ${process.env.PORT||5000}`));
